# Generated by Django 4.2.16 on 2024-10-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_description_short_places_lat_places_lon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
