# Generated by Django 4.2.16 on 2024-10-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='places',
            name='description_long',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
