# Generated by Django 4.2.16 on 2024-10-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_images_options_places_description_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Идентификатор места'),
        ),
    ]
